/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const main: (a: number, b: number) => number;
export const wasm_bindgen__closure__destroy__h2428fafa00c7cd1c: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h174c71eb9f0de202: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h1db60139b9cf621f: (a: number, b: number) => void;
export const wasm_bindgen__closure__destroy__h809d232c627c2d16: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h7aa17e64532cb69f: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h51a651ce8549df4d: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h6a6af1ce1df47988: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h6a6af1ce1df47988_2: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h6a6af1ce1df47988_3: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h6a6af1ce1df47988_4: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h3dbdccde23a4ee46: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h3dbdccde23a4ee46_7: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h3dbdccde23a4ee46_8: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h3dbdccde23a4ee46_9: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h3dbdccde23a4ee46_10: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h3dbdccde23a4ee46_11: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h3dbdccde23a4ee46_12: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h3dbdccde23a4ee46_13: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h8104105b8b901ed5: (a: number, b: number, c: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h1afdef1d511a2e1f: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h7d0bfc3a32a2985d: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
